"""
APIs 28-33: Developer Utilities & Document Tools
"""
import io
import base64
import hashlib
import string
import random
from datetime import datetime
from fastapi import APIRouter, HTTPException, Query, UploadFile, File
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/api/tools", tags=["Developer Utilities & Document Tools"])

# In-memory short URL store (use Redis/DB in production)
_url_store: dict = {}
_click_store: dict = {}


# ── 28 PDF Generator / HTML-to-PDF ───────────────────────────────────────────

class PDFIn(BaseModel):
    html: Optional[str] = None
    url: Optional[str] = None
    template: Optional[str] = "invoice"  # invoice | report | blank
    title: Optional[str] = "Document"
    data: Optional[dict] = {}

@router.post("/pdf", summary="28 · PDF Generator / HTML-to-PDF API")
def generate_pdf(payload: PDFIn):
    """Convert HTML, URLs, or Markdown templates to pixel-perfect PDFs."""
    try:
        import weasyprint

        if payload.url:
            html_content = f"<html><body><iframe src='{payload.url}'></iframe></body></html>"
        elif payload.html:
            html_content = payload.html
        else:
            # Pre-built templates
            data = payload.data or {}
            if payload.template == "invoice":
                html_content = f"""
                <html><head><style>
                body{{font-family:Arial,sans-serif;margin:40px;color:#333}}
                .header{{background:#2563eb;color:white;padding:20px;border-radius:8px}}
                table{{width:100%;border-collapse:collapse;margin-top:20px}}
                th,td{{border:1px solid #ddd;padding:10px;text-align:left}}
                th{{background:#f1f5f9}}
                .total{{font-size:1.2em;font-weight:bold;color:#2563eb}}
                </style></head><body>
                <div class="header"><h1>INVOICE</h1><p>Invoice #: {data.get('invoice_no','INV-001')}</p></div>
                <p><strong>Date:</strong> {data.get('date', datetime.now().strftime('%Y-%m-%d'))}</p>
                <p><strong>Bill To:</strong> {data.get('client','Client Name')}</p>
                <table>
                <tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
                <tr><td>{data.get('item','Service')}</td><td>{data.get('qty',1)}</td>
                    <td>${data.get('price','0.00')}</td><td>${data.get('total','0.00')}</td></tr>
                </table>
                <p class="total">Total Due: ${data.get('total','0.00')}</p>
                </body></html>"""
            else:
                html_content = f"<html><body><h1>{payload.title}</h1><p>Generated by RapidAPI Platform</p></body></html>"

        pdf = weasyprint.HTML(string=html_content).write_pdf()
        pdf_b64 = base64.b64encode(pdf).decode()
        return {
            "status": "success",
            "api": "PDF Generator",
            "title": payload.title,
            "template": payload.template,
            "pdf_base64": pdf_b64,
            "size_bytes": len(pdf),
            "usage": "Decode base64 and save as .pdf",
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(exc)}")


# ── 29 OCR / Image-to-Text ────────────────────────────────────────────────────

@router.post("/ocr", summary="29 · OCR / Image-to-Text API")
async def ocr_image(
    file: UploadFile = File(...),
    language: str = Query("eng", description="Tesseract language code e.g. eng, ara, fra"),
):
    """Extract text from images, scanned documents, receipts, and business cards."""
    try:
        import pytesseract
        from PIL import Image

        contents = await file.read()
        img = Image.open(io.BytesIO(contents))
        text = pytesseract.image_to_string(img, lang=language)
        data = pytesseract.image_to_data(img, lang=language, output_type=pytesseract.Output.DICT)
        words = [w for w in data["text"] if w.strip()]
        confidences = [c for c, w in zip(data["conf"], data["text"]) if w.strip() and c > 0]
        avg_conf = sum(confidences) / len(confidences) if confidences else 0

        return {
            "status": "success",
            "api": "OCR / Image-to-Text",
            "filename": file.filename,
            "language": language,
            "extracted_text": text.strip(),
            "word_count": len(words),
            "confidence": round(avg_conf, 1),
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"OCR failed: {str(exc)}")


# ── 30 Barcode & QR Code ──────────────────────────────────────────────────────

class QRIn(BaseModel):
    data: str
    qr_type: Optional[str] = "qr"  # qr | ean13 | ean8 | code128 | upca
    size: Optional[int] = 10
    border: Optional[int] = 4

@router.post("/qrcode", summary="30 · Barcode & QR Code API — Generate")
def generate_qrcode(payload: QRIn):
    """Generate and decode barcodes (EAN, UPC, Code128) and QR codes."""
    try:
        if payload.qr_type == "qr":
            import qrcode
            qr = qrcode.QRCode(
                version=1,
                box_size=payload.size or 10,
                border=payload.border or 4,
                error_correction=qrcode.constants.ERROR_CORRECT_M,
            )
            qr.add_data(payload.data)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            img_b64 = base64.b64encode(buf.getvalue()).decode()
            return {
                "status": "success",
                "api": "QR Code Generator",
                "type": "QR",
                "data": payload.data,
                "image_base64": img_b64,
                "format": "png",
            }
        else:
            import barcode
            from barcode.writer import ImageWriter
            barcode_class = barcode.get_barcode_class(payload.qr_type)
            buf = io.BytesIO()
            barcode_class(payload.data, writer=ImageWriter()).write(buf)
            img_b64 = base64.b64encode(buf.getvalue()).decode()
            return {
                "status": "success",
                "api": "Barcode Generator",
                "type": payload.qr_type.upper(),
                "data": payload.data,
                "image_base64": img_b64,
                "format": "png",
            }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Code generation failed: {str(exc)}")


@router.post("/qrcode/decode", summary="30b · Barcode & QR Code — Decode")
async def decode_qrcode(file: UploadFile = File(...)):
    """Decode QR codes and barcodes from uploaded images."""
    try:
        from PIL import Image
        from pyzbar.pyzbar import decode
        contents = await file.read()
        img = Image.open(io.BytesIO(contents))
        decoded = decode(img)
        results = [{"data": d.data.decode("utf-8"), "type": d.type} for d in decoded]
        return {
            "status": "success",
            "api": "QR/Barcode Decoder",
            "found": len(results),
            "results": results,
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Decode failed: {str(exc)}")


# ── 31 Screenshot / Website Capture ──────────────────────────────────────────

@router.get("/screenshot", summary="31 · Screenshot / Website Capture API")
async def screenshot_url(
    url: str = Query(..., description="URL to capture"),
    width: int = Query(1280, description="Viewport width"),
    height: int = Query(720, description="Viewport height"),
    full_page: bool = Query(False, description="Capture full page"),
    device: str = Query("desktop", description="Device: desktop | mobile | tablet"),
):
    """Take full-page or viewport screenshots of any URL as PNG."""
    try:
        from playwright.async_api import async_playwright
        async with async_playwright() as p:
            devices_map = {
                "mobile": {"width": 375, "height": 812},
                "tablet": {"width": 768, "height": 1024},
                "desktop": {"width": width, "height": height},
            }
            vp = devices_map.get(device, {"width": width, "height": height})
            browser = await p.chromium.launch(args=["--no-sandbox", "--disable-setuid-sandbox"])
            page = await browser.new_page(viewport=vp)
            await page.goto(url, wait_until="networkidle", timeout=30000)
            screenshot = await page.screenshot(full_page=full_page)
            await browser.close()
        img_b64 = base64.b64encode(screenshot).decode()
        return {
            "status": "success",
            "api": "Screenshot / Website Capture",
            "url": url,
            "device": device,
            "width": vp["width"],
            "height": vp["height"],
            "full_page": full_page,
            "screenshot_base64": img_b64,
            "format": "png",
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Screenshot failed: {str(exc)}")


# ── 32 URL Shortener & Link Tracking ─────────────────────────────────────────

class ShortIn(BaseModel):
    url: str
    custom_slug: Optional[str] = None
    utm_source: Optional[str] = None
    utm_medium: Optional[str] = None
    utm_campaign: Optional[str] = None

@router.post("/shorten", summary="32 · URL Shortener & Link Tracking API")
def shorten_url(payload: ShortIn, request_base: str = "https://rapid.short/"):
    """Shorten URLs, create custom slugs, and track click analytics."""
    slug = payload.custom_slug or hashlib.md5(payload.url.encode()).hexdigest()[:6]
    url = payload.url
    if payload.utm_source:
        sep = "&" if "?" in url else "?"
        url += f"{sep}utm_source={payload.utm_source}"
    if payload.utm_medium:
        url += f"&utm_medium={payload.utm_medium}"
    if payload.utm_campaign:
        url += f"&utm_campaign={payload.utm_campaign}"

    _url_store[slug] = {"original": url, "created_at": str(datetime.utcnow()), "clicks": 0}
    short_url = f"{request_base}{slug}"
    return {
        "status": "success",
        "api": "URL Shortener",
        "original_url": payload.url,
        "short_url": short_url,
        "slug": slug,
        "tracking_enabled": True,
    }

@router.get("/shorten/{slug}/stats", summary="32b · URL Click Stats")
def url_stats(slug: str):
    """Get click analytics for a shortened URL."""
    entry = _url_store.get(slug)
    if not entry:
        raise HTTPException(status_code=404, detail="Slug not found")
    return {
        "status": "success",
        "api": "URL Click Stats",
        "slug": slug,
        "original_url": entry["original"],
        "total_clicks": entry["clicks"],
        "created_at": entry["created_at"],
    }


# ── 33 Image Compression & Optimisation ─────────────────────────────────────

@router.post("/image-compress", summary="33 · Image Compression & Optimisation API")
async def compress_image(
    file: UploadFile = File(...),
    quality: int = Query(85, ge=1, le=100, description="Output quality (1-100)"),
    max_width: Optional[int] = Query(None, description="Max width in pixels"),
    max_height: Optional[int] = Query(None, description="Max height in pixels"),
    format: str = Query("WEBP", description="Output format: JPEG | PNG | WEBP | AVIF"),
    watermark: Optional[str] = Query(None, description="Watermark text"),
):
    """Compress, resize, convert, and watermark images on the fly."""
    try:
        from PIL import Image, ImageDraw, ImageFont

        contents = await file.read()
        img = Image.open(io.BytesIO(contents))
        original_size = len(contents)

        if img.mode in ("RGBA", "LA", "P") and format.upper() == "JPEG":
            img = img.convert("RGB")

        if max_width or max_height:
            w, h = img.size
            if max_width and w > max_width:
                ratio = max_width / w
                img = img.resize((max_width, int(h * ratio)), Image.LANCZOS)
            if max_height and img.height > max_height:
                ratio = max_height / img.height
                img = img.resize((int(img.width * ratio), max_height), Image.LANCZOS)

        if watermark:
            draw = ImageDraw.Draw(img)
            draw.text((10, 10), watermark, fill=(128, 128, 128, 128))

        buf = io.BytesIO()
        fmt = format.upper()
        if fmt == "WEBP":
            img.save(buf, format="WEBP", quality=quality, optimize=True)
        elif fmt == "JPEG":
            img.save(buf, format="JPEG", quality=quality, optimize=True)
        elif fmt == "PNG":
            img.save(buf, format="PNG", optimize=True)
        else:
            img.save(buf, format=fmt, quality=quality)

        compressed = buf.getvalue()
        compressed_b64 = base64.b64encode(compressed).decode()
        compression_ratio = round((1 - len(compressed) / original_size) * 100, 1)

        return {
            "status": "success",
            "api": "Image Compression & Optimisation",
            "original_filename": file.filename,
            "original_size_bytes": original_size,
            "compressed_size_bytes": len(compressed),
            "compression_ratio_percent": compression_ratio,
            "output_width": img.width,
            "output_height": img.height,
            "format": fmt,
            "quality": quality,
            "image_base64": compressed_b64,
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Image compression failed: {str(exc)}")
